<?php

namespace BlogBundle\Repository;

/**
 * Entry_TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntryTagRepository extends \Doctrine\ORM\EntityRepository
{
}
