blog_authors:
    path: /authors
    defaults: { _controller: BlogBundle:Author:getAuthors }
    methods: GET
blog_authors_new:
    path: /authors/new
    defaults: {_controller: BlogBundle:Author:newAuthor}
    methods: GET
