blog_authors:
    path: /authors
    defaults: { _controller: BlogBundle:Author:getAuthors }
    methods: GET

blog_authors_new:
    path: /authors/new
    defaults: {_controller: BlogBundle:Author:newAuthor}
    methods: GET

blog_author_login:
    path: /login
    defaults: {_controller: BlogBundle:Author:login}
    methods: [GET,POST]

blog_author_login_check:
    path: /login_check
    methods: POST

blog_author_logout:
    path: /logout

blog_author_registrer:
    path: /registrer
    defaults: {_controller: BlogBundle:Author:register}
    methods: GET

blog_homepage:
    path: /home
    methods: GET
    defaults: {_controller: BlogBundle:Default:home}
blog_add_tag:
    path: /addTag
    defaults: { _controller: BlogBundle:Tag:add }
    methods: [GET,POST]
blog_index_tag:
    path: /tags
    defaults: {_controller: BlogBundle:Tag:index}
    methods: GET
blog_delete_tag:
    path: /tags/delete/{id}
    defaults: {_controller: BlogBundle:Tag:delete}
add:
    path:     /addCategory
    defaults: { _controller: BlogBundle:Category:add }
