BlogBundle\Entity\Tag:
    properties:
        name:
            - NotBlank: {message: "El nobre no puede estar vacío"}
            - Length:
                min: 2
                minMessage: "El nombre tiene que tener mas de dos caracteres"