BlogBundle\Entity\Author:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\AuthorRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        role:
            type: string
            length: '20'
        name:
            type: string
            length: 255
        surname:
            type: string
            length: 255
        email:
            type: string
            length: 255
        password:
            type: string
            length: 255
        imagen:
            type: string
            length: 255
    lifecycleCallbacks: {  }
