BlogBundle\Entity\Entry:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\EntryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        content:
            type: text
        status:
            type: string
            length: 255
        image:
            type: string
            length: 255
    manyToOne:
        author:
            targetEntity: Author
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                author_id:
                    referencedColumnName: id
            orphanRemoval: false
        category:
            targetEntity: Category
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inverseBy: entry
            joinColumns:
                category_id:
                    referencedColumnName: id
    oneToMany:
        entryTag:
            targetEntity: EntryTag
            mappedBy: entry
            cascade: ["persist"]
    lifecycleCallbacks: {  }
