BlogBundle\Entity\Entry_Tag:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\Entry_TagRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        entryId:
            type: integer
            column: entry_id
        tagId:
            type: integer
            column: tag_id
    manyToOne:
        entry:

            targetEntity: Entry
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: entryTag
            joinColumns:
                entry_id:
                    referencedColumnName: id
            orphanRemoval: false
        tag:
            targetEntity: Tag
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                tag_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
