BlogBundle\Entity\EntryTag:
    type: entity
    table: entry_tag
    repositoryClass: BlogBundle\Repository\EntryTagRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        entry:
            targetEntity: Entry
            cascade: {  }
            inversedBy: entryTags
            joinColumn:
                entry_id:
                    referencedColumnName: id
        tag:
            targetEntity: Tag
            cascade: {  }
            inversedBy: entryTags
            joinColumn:
                tag_id:
                    referencedColumnName: id
    lifecycleCallbacks: {  }
